config/routes.rb
Rails.application.routes.draw do
  root 'hospitals#index'
  resources :employees do
    member do
      post :fire
      post :hire
    end
  end
  resources :hospitals

end

app/models/employee.rb
class Employee < ActiveRecord::Base
  has_many :employments, dependent: :destroy
  has_many :hospitals, through: :employments

  validates :surname, presence: true
  validates :surname, length: {minimum: 3, maximum: 20}
  validates :surname, format: {with: /[a-zA-Z\s]+/, message: 'must containe letters only!' }
  validates :birth_year, presence: true
  validates :birth_year, numericality: {only_integer: true, greater_than_or_equal_to: 1900, less_than_or_equal_to: Date.today.year+16}
  validates :position, presence: true 
  validates :position, inclusion: {in: [ 'doctor', 'assistant', 'nurse' ]}

  def self.free_employees (hospital_id)
    emp=[]
    employees=Employee.find_each do |e|
      if !e.hospitals.exists? || !e.hospitals.any? {|h| h[:id] == hospital_id}
        emp<<e
      end
    end
    emp
  end
  # def self.free_employees (hospital_id)
  #   Employee.all.joins(:hospitals).where.not(hospitals: {id:hospital_id}).uniq
  # end
end

app/models/employment.rb
class Employment < ActiveRecord::Base
  belongs_to :hospital
  belongs_to :employee
end

app/models/hospital.rb
class Hospital < ActiveRecord::Base
  has_many :employments
  has_many :employees, through: :employments

  validates :order_number, presence: true
  validates :order_number, numericality: {only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 100}
  validates :order_number, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy, :hire]

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def fire
    employment=Employment.find_by_employee_id_and_hospital_id(params[:id], params[:hospital_id])
    respond_to do |format|
    if employment.destroy
      format.html { redirect_to :back, notice: 'Employee was fired.' }
    else
      format.html { redirect_to :back, alert: 'Something went wrong!' }
    end
  end
  end

   def hire
    
    @employee.hospitals<<Hospital.find(params[:hospital_id])
    respond_to do |format|
    if @employee.save
      format.html { redirect_to :back, notice: 'Employee was hired.' }
    else
      format.html { redirect_to :back, alert: 'Something went wrong!' }
    end
  end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:surname, :birth_year, :position)
    end
end

app/controllers/hospitals_controller.rb
class HospitalsController < ApplicationController
  before_action :set_hospital, only: [:show, :edit, :update, :destroy]

  # GET /hospitals
  # GET /hospitals.json
  def index
    @hospitals = Hospital.all

  end

  # GET /hospitals/1
  # GET /hospitals/1.json
  def show
    @free_employees=Employee.free_employees(@hospital.id)
  end

  # GET /hospitals/new
  def new
    @hospital = Hospital.new
  end

  # GET /hospitals/1/edit
  def edit
  end

  # POST /hospitals
  # POST /hospitals.json
  def create
    @hospital = Hospital.new(hospital_params)

    respond_to do |format|
      if @hospital.save
        format.html { redirect_to @hospital, notice: 'Hospital was successfully created.' }
        format.json { render :show, status: :created, location: @hospital }
      else
        format.html { render :new }
        format.json { render json: @hospital.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hospitals/1
  # PATCH/PUT /hospitals/1.json
  def update
    respond_to do |format|
      if @hospital.update(hospital_params)
        format.html { redirect_to @hospital, notice: 'Hospital was successfully updated.' }
        format.json { render :show, status: :ok, location: @hospital }
      else
        format.html { render :edit }
        format.json { render json: @hospital.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hospitals/1
  # DELETE /hospitals/1.json
  def destroy
    @hospital.destroy
    respond_to do |format|
      format.html { redirect_to hospitals_url, notice: 'Hospital was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hospital
      @hospital = Hospital.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hospital_params
      params.require(:hospital).permit(:order_number)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/hospitals_helper.rb
module HospitalsHelper
end

app/views/employees/_form.html.erb
<%= form_for(@employee) do |f| %>
  <% if @employee.errors.full_messages.any? %>
  <% @employee.errors.full_messages.each do |error_message| %>
    <div class="alert alert-danger" role="alert">
    <%= error_message  %> <br />
    </div>
  <% end %>
<% end %>

  <div class="field">
    <%= f.label :surname %><br>
    <%= f.text_field :surname , class: 'form-control'%>
  </div>
  <div class="field">
    <%= f.label :birth_year %><br>
    <%= f.number_field :birth_year, class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :position %><br>
    <%= f.select :position, ['doctor','assistant','nurse'], {}, {class:"form-control"}%>
  </div>
  <div class="actions">
    <%= f.submit "Save", class: "btn btn-default" %>
  </div>
<% end %>
<!-- 

<% if @employee.errors.full_messages.any? %>
  <% @employee.errors.full_messages.each do |error_message| %>
    <div class="alert alert-danger" role="alert">
    <%= error_message if @employee.errors.full_messages.first == error_message %> <br />
    </div>
  <% end %>
<% end %>

<%= form_for(@employee) do |f|%>
  <%= f.text_field :surname, class: 'form-control' %>
  
  <%= f.number_field :birth_year, class: 'form-control' %>
  <%= f.submit "Save", class: "btn btn-default"%>
<% end %> -->

app/views/employees/edit.html.erb
<h1>Editing Employee</h1>
<%= render 'form' %>
<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Employees</h1>

<table class="table table-stripped">
  <thead>
    <tr>
      <th>Surname</th>
      <th>Birth year</th>
      <th>Position</th>
      <th>Hospitals</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.surname %></td>
        <td><%= employee.birth_year %></td>
        <td><%= employee.position %></td>
        <td><% employee.hospitals.each do |h| %>
              <%= link_to h.order_number, h %>
              <% end %>
        </td>

        <td><%= link_to 'Show', employee %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
        <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employee', new_employee_path %>

app/views/employees/new.html.erb
<h1>New Employee</h1>

<%= render 'form' %>

<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Surname:</strong>
  <%= @employee.surname %>
</p>

<p>
  <strong>Birth year:</strong>
  <%= @employee.birth_year %>
</p>

<p>
  <strong>Position:</strong>
  <%= @employee.position %>
</p>

<p>
  <strong>Hospitals:</strong>
  <% @employee.hospitals.each do |h| %>
    <%=link_to h.order_number, h %>
  <% end %>
</p>
<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>

app/views/hospitals/_form.html.erb
<%= form_for(@hospital) do |f| %>
  <% if @hospital.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hospital.errors.count, "error") %> prohibited this hospital from being saved:</h2>

      <ul>
      <% @hospital.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :order_number %><br>
    <%= f.number_field :order_number %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hospitals/edit.html.erb
<h1>Editing Hospital</h1>

<%= render 'form' %>

<%= link_to 'Show', @hospital %> |
<%= link_to 'Back', hospitals_path %>

app/views/hospitals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Hospitals</h1>

<table class="table table-stripped">
  <thead>
    <tr>
      <th>Order number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hospitals.each do |hospital| %>
      <tr>
        <td><%= hospital.order_number %></td>
        <td><%= link_to 'Show', hospital %></td>
        <td><%= link_to 'Edit', edit_hospital_path(hospital) %></td>
        <td><%= link_to 'Destroy', hospital, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hospital', new_hospital_path %>

app/views/hospitals/new.html.erb
<h1>New Hospital</h1>

<%= render 'form' %>

<%= link_to 'Back', hospitals_path %>

app/views/hospitals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Order number:</strong>
  <%= @hospital.order_number %>
</p>
<% if @hospital.employees.any? %>
  <h3>  Employees:</h3>
  <table class="table">
    <thead>
      <th>Surname</th>
      <th>Position</th>
      <th>Birth year</th>
      <th></th>
      <th></th>
      <th></th>
    </thead>
    <tbody>
      <%@hospital.employees.each  do |e|%>
      <tr>
          <td><%= e.surname %></td>
          <td><%= e.position %></td>
          <td><%= e.birth_year %></td>
          <td> <%= link_to "Show", e %></td>
          <td><%= link_to 'Fire', fire_employee_path(e, hospital_id: @hospital.id), method: :post%></td>
      </tr>
      <% end %> 
    </tbody>
  </table>
<% else %>
<h3>Nobody works in this hospital!</h3>
<% end %>
<%if @free_employees.any? %>
  <h3>You can hire any of above:</h3>
  <table class="table">
    <thead>
      <th>Surname</th>
      <th>Position</th>
      <th>Birth year</th>
      <th></th>
      <th></th>
      <th></th>
    </thead>
    <tbody>
      <%@free_employees.each do |f| %>
      <tr>
          <td><%= f.surname %></td>
          <td><%= f.position %></td>
          <td><%= f.birth_year %></td>
          <td> <%= link_to "Show", f %></td>
          <td><%= link_to 'Hire', hire_employee_path(f, hospital_id: @hospital.id), method: :post%></td>
      </tr>
      <% end %> 
    </tbody>
  </table>
<% else %>
<h3>No employees are free to hire!</h3>
<% end %>
<%= link_to 'Edit', edit_hospital_path(@hospital) %> |
<%= link_to 'Back', hospitals_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MedApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<p>
  <%= link_to 'Hospitals', hospitals_path %>|
  <%= link_to 'Employees', employees_path %>
</p>
<%= yield %>

</body>
</html>